### ISSUE TITLE
New contact creation

### ISSUE THREAD

**Issue by nikitamankovskii** [ingbrzy/MA-XML-12-RUSSIAN#33]
Just closing the contact app on creating

Here is report:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void miui.widget.CheckedTextView.setChecked(boolean)' on a null object reference
	at com.android.contacts.util.AccountsListAdapter.getView(Unknown Source:172)
	at android.widget.AbsListView.obtainView(Unknown Source:66)
	at android.widget.ListView.measureHeightOfChildren(Unknown Source:58)
	at android.widget.ListView.onMeasure(Unknown Source:160)
	at android.view.View.measure(Unknown Source:221)
	at android.view.ViewGroup.measureChildWithMargins(Unknown Source:42)
	at android.widget.LinearLayout.measureChildBeforeLayout(Unknown Source:6)
	at android.widget.LinearLayout.measureVertical(Unknown Source:249)
	at android.widget.LinearLayout.onMeasure(Unknown Source:5)
	at android.view.View.measure(Unknown Source:221)
	at android.view.ViewGroup.measureChildWithMargins(Unknown Source:42)
	at android.widget.LinearLayout.measureChildBeforeLayout(Unknown Source:6)
	at android.widget.LinearLayout.measureVertical(Unknown Source:249)
	at android.widget.LinearLayout.onMeasure(Unknown Source:5)
	at com.miui.internal.widget.DialogParentPanel.onMeasure(Unknown Source:8)
	at android.view.View.measure(Unknown Source:221)
	at android.view.ViewGroup.measureChildWithMargins(Unknown Source:42)
	at android.widget.FrameLayout.onMeasure(Unknown Source:82)
	at android.view.View.measure(Unknown Source:221)
	at android.view.ViewGroup.measureChildWithMargins(Unknown Source:42)
	at com.miui.internal.widget.ActionBarOverlayLayout.onMeasure(Unknown Source:457)
	at android.view.View.measure(Unknown Source:221)
	at android.view.ViewGroup.measureChildWithMargins(Unknown Source:42)
	at android.widget.FrameLayout.onMeasure(Unknown Source:82)
	at com.android.internal.policy.DecorView.onMeasure(Unknown Source:308)
	at android.view.View.measure(Unknown Source:221)
	at android.view.ViewRootImpl.performMeasure(Unknown Source:15)
	at android.view.ViewRootImpl.measureHierarchy(Unknown Source:100)
	at android.view.ViewRootImpl.performTraversals(Unknown Source:533)
	at android.view.ViewRootImpl.doTraversal(Unknown Source:31)
	at android.view.ViewRootImpl$TraversalRunnable.run(Unknown Source:2)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer.doCallbacks(Unknown Source:79)
	at android.view.Choreographer.doFrame(Unknown Source:182)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:9)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:242)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)

```

**Comment by mclaude74** [comment]
@nikitamankovskii 
Эта проблема не относится к переводу.
Отписаться по проблеме можно на xiaomi.eu в теме [недельной прошивки](https://xiaomi.eu/community/threads/20-7-23.56727/) или в теме [проблем](https://xiaomi.eu/community/threads/weekly-confirmed-issues-faq.46800/).

**Comment by nikitamankovskii** [comment]
@mclaude74 Хорошо, спасибо
